### ISSUE TITLE
Quest shards not recognized and just disappear

### ISSUE THREAD

**Issue by Battousai124** [Void-Crew-Modding-Team/DelayedShards#1]
Quest shards from the Container Hunt, or Log Quest Objectives, just disappear and therefore the targets cant be fulfilled.

It has with the mod installed and enabled, so far, happened with every single one.

**Comment by 18107** [comment]
This is a bug in the base game. You can find more information on the official Void Crew discord.
https://discord.com/channels/814811296390053888/1261485327491661894
